 title: Jiří Říha
 remote_theme: Minimal
<style>
body {
  background-image: url("immage.pdf");
  background-size: cover;
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center;
}
</style>
